/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xdump_android_zinnia_Zinnia */

#ifndef _Included_org_xdump_android_zinnia_Zinnia
#define _Included_org_xdump_android_zinnia_Zinnia
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_character_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1character_1new
  (JNIEnv *, jobject);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_character_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1character_1destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_character_set_value
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1character_1set_1value
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_character_set_value2
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1character_1set_1value2
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_character_value
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1character_1value
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_character_set_width
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1character_1set_1width
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_character_set_height
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1character_1set_1height
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_character_width
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1character_1width
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_character_height
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1character_1height
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_character_clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1character_1clear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_character_add
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1character_1add
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_character_strokes_size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1character_1strokes_1size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_character_stroke_size
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1character_1stroke_1size
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_character_x
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1character_1x
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_character_y
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1character_1y
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_character_parse
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1character_1parse
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_character_parse2
 * Signature: (JLjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1character_1parse2
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_character_to_string
 * Signature: (JLjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1character_1to_1string
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_character_strerror
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1character_1strerror
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_result_value
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1result_1value
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_result_score
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1result_1score
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_result_size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1result_1size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_result_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1result_1destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_recognizer_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1recognizer_1new
  (JNIEnv *, jobject);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_recognizer_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1recognizer_1destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_recognizer_open
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1recognizer_1open
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_recognizer_open_from_ptr
 * Signature: (JLjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1recognizer_1open_1from_1ptr
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_recognizer_close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1recognizer_1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_recognizer_size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1recognizer_1size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_recognizer_value
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1recognizer_1value
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_recognizer_strerror
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1recognizer_1strerror
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_recognizer_classify
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1recognizer_1classify
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_trainer_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1trainer_1new
  (JNIEnv *, jobject);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_trainer_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1trainer_1destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_trainer_add
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1trainer_1add
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_trainer_clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1trainer_1clear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_trainer_train
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1trainer_1train
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_trainer_strerror
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1trainer_1strerror
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_trainer_convert_model
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1trainer_1convert_1model
  (JNIEnv *, jobject, jstring, jstring, jdouble);

/*
 * Class:     org_xdump_android_zinnia_Zinnia
 * Method:    zinnia_trainer_make_header
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_org_xdump_android_zinnia_Zinnia_zinnia_1trainer_1make_1header
  (JNIEnv *, jobject, jstring, jstring, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
